[package]
name = "emutk-testing"
version = "0.1.0"
authors = ["moonheart08 <moonheart08@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.2.0"
emutk-core = { path = "../emutk-core" }
emutk-vax = { path = "../emutk-vax" }